services:
  - docker:dind

stages:
  - test
  - build
  - deploy

lint-test-job:
  image: python:3-bullseye
  stage: test
  script:
    - pip install flake8
    - flake8 api
  only:
    - main

api-unit-tests-job:
  image: python:3-bullseye
  stage: test
  needs:
    - lint-test-job
  variables:
    MONGO_USER: "DOESNOTMATTER"
    MONGO_PASSWORD: "DOESNOTMATTER"
    MONGO_HOST: "DOESNOTMATTER"
    MONGO_DB: "DOESNOTMATTER"
    SIGNING_KEY: "DOESNOTMATTER"
  script:
    - cd api
    - pip install -r requirements.txt
    - python -m pytest
  only:
    - main

build-api-image:
  stage: build
  image: docker:git
  variables:
    GITLAB_IMAGE: ${CI_REGISTRY_IMAGE}/api_image
  before_script:
    # $CI_JOB_TOKEN is variable automatically added by Gitlab: see https://docs.gitlab.com/ee/ci/variables/predefined_variables.html#variables-reference
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin
  script:
    - docker build --tag $GITLAB_IMAGE:latest ./api
    - docker push $GITLAB_IMAGE:latest
  only:
    - main

# Build the React/JavaScript front-end
build-front-end-job:
  stage: build
  only:
    - main
  image: node:lts-bullseye
  needs:
    - lint-test-job
    - api-unit-tests-job
  variables:
    PUBLIC_URL: https://penguins.gitlab.io/bookbounty
    REACT_APP_API_HOST: https://feb-23-ct-6-bookbounty-api.mod3projects.com
  script:
    - cd ghi
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - ghi/build/

# Deploy the React/JavaScript front-end to GitLab pages
pages:
  stage: deploy
  only:
    - main
  dependencies:
    - build-front-end-job
  needs:
    - build-front-end-job
  script:
    - mv ghi/build/ public
  artifacts:
    paths:
      - public
